spring:
  application:
    name: spring-cloud-itoken-service-admin
  boot:
    admin:
      client:
        url: localhost:8084
  zipkin:
    base-url: localhost:9411
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/spring-cloud-itoken-service-admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8501

mybatis:
  type-aliases-package: com.sfz.spring.cloud.itoken.service.admin.domain
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: localhost:8761/eureka/,localhost:8861/eureka/,localhost:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info